test:
  service: Disk
  public: true
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  public: true
  root: <%= Rails.root.join("storage") %>

# # Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= ENV['BUCKETEER_AWS_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['BUCKETEER_AWS_SECRET_ACCESS_KEY'] %>
#   region: <%= ENV['BUCKETEER_AWS_REGION'] %>
#   bucket: <%= ENV['BUCKETEER_BUCKET_NAME'] %>
#   public: true
#   upload:
#     cache_control: 'public, max-age=31536000'

google:
  service: GCS
  project: darek-business
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: darek-shop-1

google_dev:
  service: GCS
  project: darek-business
  credentials: <%= Rails.root.join("config/secrets/darek-business.json") %>
  bucket: darek-shop-1
